### ISSUE TITLE
JSON schema extracted from pydantic seems to be missing relationship fields.

### ISSUE THREAD

**Issue by stuartlynn** [Urban-Analytics-Technology-Platform/popgetter-cli#13]
SourceReleaseMetadata seems to be missing the relationship fields like available metrics 

https://github.com/Urban-Analytics-Technology-Platform/popgetter-cli/blob/66a295f2903739b4aa880dfd028e6c19165c6fee/schema.json#L71-L182

Need to check to see if this is true of the export function that @yongrenjie has in the pipeline code and if so figure out why they are missing.

**Comment by yongrenjie** [comment]
> if so figure out why they are missing.

It's commented out in the main branch:

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L58-L60

That said ... I personally think it's better to not have this field because it leads to cyclic references that have to be updated in tandem. To find the list of metrics that correspond to this source data release, it's better to query a list of MetricMetadata to see which of them correspond to this source data release

**Comment by penelopeysm** [comment]
No longer relevant as we aren't using the exported schema json / the schema has changed anyway
